# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170909_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 9, 15, 41, 17, 509948, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.New'),
        ),
    ]
