# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170909_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 10, 21, 6, 26, 462798, tzinfo=utc)),
        ),
    ]
